name: Deploy Static Site to S3

on:
  push:
    branches:
      - upload

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: my_web_page/node_modules
        key: yarn-deps-${{ hashFiles('my_web_page/yarn.lock') }}
        restore-keys: |
          yarn-deps-${{ hashFiles('my_web_page/yarn.lock') }}

    - name: Install dependencies
      run: npm install
      working-directory: my_web_page

    - name: Build app
      run: npm run build
      working-directory: my_web_page

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to S3
      run: |
        aws s3 sync ../../build s3://brynnpark.cloud
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
