name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform-setting:
    name: Terraform Apply - Depoly
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform for the "setting" environment
      - name: Terraform Init
        working-directory: ./terraform/depoly
        run: terraform init

      # Plan Terraform changes for the "setting" environment
      - name: Terraform Plan
        working-directory: ./terraform/depoly
        run: terraform plan

      # Apply Terraform changes for the "setting" environment
      - name: Terraform Apply
        working-directory: ./terraform/depoly
        run: terraform apply -auto-approve

  terraform-upload:
    name: Terraform Apply - Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform for the "upload" environment
      - name: Terraform Init
        working-directory: ./terraform/upload
        run: terraform init

      # Plan Terraform changes for the "upload" environment
      - name: Terraform Plan
        working-directory: ./terraform/upload
        run: terraform plan

      # Apply Terraform changes for the "upload" environment
      - name: Terraform Apply
        working-directory: ./terraform/upload
        run: terraform apply -auto-approve